### ISSUE TITLE
Toggle for filtering results from known buckets

### ISSUE THREAD

**Issue by rashil2000** [ScoopSearch/ScoopSearch.WebSearchEngine#1]
Hi!

I'm here from https://github.com/ScoopInstaller/Scoop/issues/4627#issuecomment-1012173950, and I wanted to ask whether a toggle/checkbox that could be added to only show search results from known buckets, somewhere in the middle here:

![image](https://user-images.githubusercontent.com/46838874/149575287-9bfce716-df2b-426b-868d-c84d8f2114fb.png)

(I'm aware that the results are already sorted to show known buckets first, but still.)

Cheers!

**Comment by gpailler** [comment]
Hey @rashil2000 , 

Thanks for your request. The information about the bucket source type is already stored in the index so it should be quite straight-forward. I will try to take a look and add this toggle.

**Comment by rashil2000** [comment]
Thanks for the update! Looking forward to it :)

**Comment by gpailler** [comment]
I just pushed a new version with a toggle to search only in the official buckets
![image](https://user-images.githubusercontent.com/3621529/149626328-2c33a253-27fe-4381-ba82-98754637f6be.png)

I'm open to your suggestions as I'm not fully happy with the placement/wording.

**Comment by rashil2000** [comment]
Hmm, I have a couple of thoughts:
- Maybe we can put it in the center (above pagination links)
- I think "Search only known buckets" is a more descriptive label

**Comment by gpailler** [comment]
I tried to put the switch in the center but it doesn't look nice and is too distractive. I ended up with a placement on the right with your label and it looks way better. 

![image](https://user-images.githubusercontent.com/3621529/149666845-2d02d0fb-ec7f-4fb3-98db-263a619c4804.png)

What are your thoughts?

**Comment by rashil2000** [comment]
To me it looks asymmetrical (sparse on left and congested on right). But if there's no other way, it's understandable.

**Comment by gpailler** [comment]
Yep, I prefer to keep the sorting/filtering options in the same area even if it makes the display slightly asymmetrical. It doesn't look too disturbing to me 👍

**Comment by rashil2000** [comment]
No worries, thanks for the quick turnaround on implementing this request ❤️

Should I close this?

**Comment by gpailler** [comment]
You're welcome! I let you close this request...
