### ISSUE TITLE
UX lift-up

### ISSUE THREAD

**Issue by JanPokorny** [ScoopSearch/ScoopSearch.WebSearchEngine#11]
I feel that there is a room for improvement with the current UI/UX.

- The page header (eg. everything above the first search result) is large, taking up to a half of the height of smaller screens. Given that it consists mostly of empty space, compacting the layout a bit could leave more of the page for search results.
	- I'd consider removing the top pagination control altogether, putting the dropdown and the toggle on a single line right under the search field to make them feel more connected with the search field, and centering the "result count" line.
- The result items are overcrowded with text.
	- Some text can be made into icons (homepage, manifest link etc.)
	- IMO some of the fields aren't strictly necessary, considering the use-case:
		- "commiter" carries very little meaning, as well as the link "commit" (feel free to explain the reasoning tho, maybe I just don't get it)
		- star count for official buckets -- the blue mark should be enough, I'd even consider dropping star count everywhere and creating a new "popular community bucket" mark that would show for buckets with >50 stars, so there's only one thing displayed next to a bucket name
			- I also had the idea that bucket could be moved to the header instead of version, like "**firefox** in _extras_ ✅", eliminating the need to duplicate the checkmark to the header
	-  "updated" could show just "x time ago" which is more readable than an absolute date
- The layout feels misaligned -- most elements in the result item don't align with each other
- One thing I think is missing is easily available `scoop bucket add x`, like shovel.sh has -- I know that there's a button for it on unofficial buckets, but even official buckets need adding the first time

To present a more clear "vision", a result item could look rougly like this.

Official bucket (short bucket name in title):

<table>
<tr>
	<td> 🖼️ <b>firefox</b> in <a href="https://github.com/ScoopInstaller/Extras" title="official bucket">extras ✅</a>
	<td align=right> 📜 <a href="https://spdx.org/licenses/MPL-2.0.html">MPL-2.0</a> | 🌍 <a href="https://www.mozilla.org/firefox/">mozilla.org/firefox</a>
<tr>
	<td> Popular open source web browser.
	<td> <code>> scoop bucket add extras</code> 📋
<tr>
	<td> <a href="https://github.com/ScoopInstaller/Extras/blob/master/bucket/firefox.json">v96.0.3 (updated 6 days ago)</a>
	<td> <code>> scoop install firefox</code> 📋
</table>

Unofficial bucket (full bucket name, star count in tooltip, different icon if >50 stars):

<table>
<tr>
	<td> 🖼️ <b>firefox</b> in <a href="#" title="community bucket with 14 stars">JanPokorny/SomeBucketIMadeUp❓</a>
	<td align=right> 📜 <a href="https://spdx.org/licenses/MPL-2.0.html">MPL-2.0</a> | 🌍 <a href="https://www.mozilla.org/firefox/">mozilla.org/firefox</a>
<tr>
	<td> Popular open source web browser.
	<td> <code>> scoop bucket add SomeBucketIMadeUp https://github.com/JanPokorny/SomeBucketIMadeUp</code> 📋
<tr>
	<td> <a href="https://github.com/ScoopInstaller/Extras/blob/master/bucket/firefox.json">v96.0.3 (updated 6 days ago)</a>
	<td> <code>> scoop install firefox</code> 📋
</table>

**Comment by gpailler** [comment]
Thanks a lot for this feedback. 

There is definitely room for improvement and your points are quite interesting. We will try to improve the UX/UI according to your proposals 👍 

Thanks

**Comment by gpailler** [comment]
Hey @JanPokorny,

I started to apply some of your UI/UX proposals to the search results. Could you take a look on the video attached and give me your early feedback? 

- top pagination control removed
- new search result layout according to your proposal
- stars removed and replaced with popular community bucket icon

Remaining parts:
- compacting layout
- responsive 
- compacting search bar + search options

I think this new layout is much more appealing than the previous one. I' m just not convinced with the `> scoop bucket add ...` displayed everywhere (as it's an action you' re doing only once per bucket)


https://user-images.githubusercontent.com/3621529/152723282-b0cea2e6-4ac0-4858-b9a4-71a1304ab67b.mp4

**Comment by JanPokorny** [comment]
@gpailler Great work! I am glad that you liked the proposal and implemented it!

---

When I look at it now, I think it might look slightly more logical if the licence+homepage and version+lastchanged were swapped, since the version ties to the app name and bucket, whereas the homepage ties more to the description. Like this (I also put homepage first since it seems more interesting of the two, and added a "package" icon before version since pretty much everything else has an icon):

<table>
<tr>
	<td> 🖼️ <b>firefox</b> in <a href="https://github.com/ScoopInstaller/Extras" title="official bucket">extras ✅</a>
	<td align=right> <a href="https://github.com/ScoopInstaller/Extras/blob/master/bucket/firefox.json">📦 v96.0.3 (updated 6 days ago)</a>
<tr>
	<td> Popular open source web browser.
	<td> <code>> scoop bucket add extras</code> 📋
<tr>
	<td> 🌍 <a href="https://www.mozilla.org/firefox/">mozilla.org/firefox</a> <br> 📜 <a href="https://spdx.org/licenses/MPL-2.0.html">MPL-2.0</a>
	<td> <code>> scoop install firefox</code> 📋
</table>

---

With the bucket URL, I see what you mean. The current control for presenting the scoop commands is visually heavy, thus having two of them makes the layout feel unbalanced. Perhaps making it more subtle (remove borders, tone down background, instead differentiate by using a monospace font), and higlighting/bolding the more important one, could look better? Like this (yes I did just shamelessly copy shovel.sh): 
![obrazek](https://user-images.githubusercontent.com/4580066/152792034-7644dbcc-37c1-4f87-a2b8-7e2548b8c085.png)

**Comment by gpailler** [comment]
Thanks for the feedback @JanPokorny.

I applied most of the changes, and you can test the dev version on https://scoopsearch.github.io/scoopsearch-dev.github.io/.

- Icons are replaced with lighter versions
- Margins are reduced and consistent between header and body
- Last update/Version are swapped with Homepage/License
  - Having the Version in last position makes it more readable according to my tests
- Overlays are available on the Verified icon, Last update and Homepage (if truncated) to display extra information (repo type, stars, full date, full url)
- Organization part is removed from Official repositories
- Scheme and trailing slash are stripped off from the Homepage url
- License is clickable (if it's a known SPDX license) 
- Copy controls are lighter

I think we are moving to the right direction 👍

**Comment by JanPokorny** [comment]
@gpailler Definitely moving in the right direction!

---

IMO it would look better if the bottoms of the two columns were aligned in the "usual" case, that is one-line description.

![obrazek](https://user-images.githubusercontent.com/4580066/153157179-570b0dd1-03ea-4641-8520-37e8f54c8c09.png)

The command font size is smaller than the rest (most is 16px, command is 14px), which looks weird. What about 16px font and 1.7 line height?

![obrazek](https://user-images.githubusercontent.com/4580066/153157722-3844d3b8-9aa6-47d2-a6d2-90194324d5bb.png)

Alternatively, this is a 14px monospace variant with 2.0 line height. I prefer light/bold to opacity, since the semi-transparent field gives off a "disabled form control" vibe.

![obrazek](https://user-images.githubusercontent.com/4580066/153156760-a171ed4f-b42e-4c46-80a9-345de8928ed2.png)

---

I also think it would be nice if the commands would react to click -- either select the command on click for easier copying, or outright make the whole thing act as the copy button and copy it on click. (I don't really see a use case for selecting just a part of the command...)

**Comment by gpailler** [comment]
According to your comments, I pushed some changes on https://scoopsearch.github.io/scoopsearch-dev.github.io/.

What are your thoughts?

**Comment by JanPokorny** [comment]
It's great!

I noticed a little visual bug (probably browser specific) -- a vertical line after `>` caused by the elements overlapping their semi-transparent backgrounds:
![obrazek](https://user-images.githubusercontent.com/4580066/153388035-8b867ebd-fab7-4f3d-bb51-6c9121205082.png)
Simply set the background to a static color (`#f7f7f7`) to stop this.

I'd also put `user-select: none` on both `#user-command-prefix` and `#user-command-text`, add a tooltip with "Click to copy" (and perhaps "Copied!" after clicking?), and changed the after-copy checkmark color to green to make it more apparent what's happening.

**Comment by gpailler** [comment]
Thanks for the feedback. I'm really not that good with this kind of small CSS details...
I fixed all the small discrepancies with the copy commands. Looks good !

**Comment by JanPokorny** [comment]
@gpailler You did great work! I think the new search result is pretty and functional. @rashil2000 any thoughts from you?

---

I found a tooltip bug when the star count is 0:
https://scoopsearch.github.io/scoopsearch-dev.github.io/#/apps?q=dolphin-nightly
![obrazek](https://user-images.githubusercontent.com/4580066/153627947-f2ab1db5-d7a4-4e31-beec-2864830dac79.png)

---

Also I noticed that the wording on the toggle is "Search only _known_ buckets", whereas the tooltips use "_Official_ bucket". I know that Scoop uses "known", but I'd stick to "official" here since it better carries the meaning.

---

Regarding my original suggestions on the search bar controls, do you have any thoughts? My idea was moving them to the center like this, to make the controls more connected, but I suppose there might be better way. I also think that it's worth it to make the page a bit more welcoming if someone stumbles upon it by accident -- by placing one sentence describing what it is.

![obrazek](https://user-images.githubusercontent.com/4580066/153631766-e968a106-f926-4f83-8a18-af21a2212d82.png)

The words "apps" (forgot to link that one 😅) and "buckets" would replace the current buttons. (Also please excuse that this is super misaligned because it is composed mostly in MSPaint 😁)

**Comment by rashil2000** [comment]
Looks awesome to me. Just one minor comment: in the overhaul, I feel we lost one bit of information: latest commit link. It should be easy to turn the following text into a hyperlink pointing to the commit, no?

![image](https://user-images.githubusercontent.com/46838874/153708313-84f8f5f3-4c86-49ff-b45e-128368a0fb71.png)

**Comment by rashil2000** [comment]
> I also think that it's worth it to make the page a bit more welcoming if someone stumbles upon it by accident -- by placing one sentence describing what it is.

I think this might not be required once the website has a homepage?

**Comment by rashil2000** [comment]
> One can still link to the search page directly

Hmm. But I'm not a fan of cluttering up the titlebar. Maybe we can put something directly above the search box?

**Comment by JanPokorny** [comment]
@rashil2000 What about not showing results when nothing is typed in, and instead showing a short message? There could be a small link under it to browse all apps (hide the message and go back to old behavior) to not lose the functionality

**Comment by rashil2000** [comment]
Hmm, seems good to me

**Comment by gpailler** [comment]
Hello guys


> I found a tooltip bug when the star count is 0:

Thanks. Fixed 

> Also I noticed that the wording on the toggle is "Search only known buckets", whereas the tooltips use "Official bucket"

Correct, I changed Known to Official as it's the word we are using everywhere.

> Regarding my original suggestions on the search bar controls, do you have any thoughts?

I'm not convinced by having the filtering/sorting controls centered below the search bar. I would rather go with a single "Options" dropdown next to the search bar containing all the sorting and filtering options. I will try to propose a mockup a bit later.

> Looks awesome to me. Just one minor comment: in the overhaul, I feel we lost one bit of information: latest commit link. It should be easy to turn the following text into a hyperlink pointing to the commit, no?

The diff link was not really useful to me as you have the manifest link already but it's quite easy to re-add it. Something like that?
![image](https://user-images.githubusercontent.com/3621529/153737417-f8ef9428-7025-468e-9483-12c1ee4696db.png)

> What about not showing results when nothing is typed in, and instead showing a short message? 

Well, the only goal of showing results without any search was to showcase the results display so the user can see what he can expect. But yes, we can just display the number of manifests indexed and a small appealing message instead

**Comment by rashil2000** [comment]
> The diff link was not really useful to me as you have the manifest link already but it's quite easy to re-add it. Something like that? ![image](https://user-images.githubusercontent.com/3621529/153737417-f8ef9428-7025-468e-9483-12c1ee4696db.png)

Yep, precisely!

I agree very less people will use it (which includes me 😅), but I have gotten similar requests in the past (see https://github.com/ScoopInstaller/Scoop/issues/4448) so I thought why not just use the information we already have in the JSON.

**Comment by gpailler** [comment]
@rashil2000 Deal 🤝 ! You can take a look on https://scoopsearch.github.io/scoopsearch-dev.github.io for the result.

**Comment by gpailler** [comment]
> > Regarding my original suggestions on the search bar controls, do you have any thoughts?
> 
> I'm not convinced by having the filtering/sorting controls centered below the search bar. I would rather go with a single "Options" dropdown next to the search bar containing all the sorting and filtering options. I will try to propose a mockup a bit later.

@JanPokorny What about an options menu like this one?
![msedge_urz7nUe2HI](https://user-images.githubusercontent.com/3621529/153741981-47e5d32e-e156-4c2f-90f0-1b67f694d0af.gif)
With a menu like this one, we can sort by ascending or descending order, and we can add other filters without overcrowding the UI. It makes the sorters/filters less discoverable though, but I think that in most cases, you don't need to change these options when you are looking for a specific app (the general use case)

**Comment by rashil2000** [comment]
> @rashil2000 Deal 🤝 ! You can take a look on https://scoopsearch.github.io/scoopsearch-dev.github.io for the result.

Yep, awesome ♥

> With a menu like this one, we can sort by ascending or descending order, and we can add other filters without overcrowding the UI. It makes the sorters/filters less discoverable though, but I think that in most cases, you don't need to change these options when you are looking for a specific app (the general use case)

How about we keep the official-bucket toggle outside but keep the filtering option inside the dropdown menu? This is to maintain symmetry with the `Found 14 applications for 'fiefox'.` text on the left.

**Comment by JanPokorny** [comment]
@gpailler I love the drop-down menu! You're right that the options are now more hidden, but it elegantly solves the layout. I'd also consider having the drop-down button in the right top corner of the search results, with a longer title like "Sorting & Filtering" to make it more noticeable. This would maintain symmetry as @rashil2000 proposed (I don't really like the idea to separate the toggle)

**Comment by gpailler** [comment]
@rashil2000 @JanPokorny New unified sorting/filtering dropdown is available on https://scoopsearch.github.io/scoopsearch-dev.github.io/

Any thoughts?

**Comment by JanPokorny** [comment]
@gpailler The only little thing I noticed is that the cursor changes to pointer inconsistently when hovering the "official bucket" toggle (both text and the toggle itself)

**Comment by gpailler** [comment]
@JanPokorny You were right, as usual ;-) The issue with the cursor is fixed

**Comment by rashil2000** [comment]
@JanPokorny should we merge the develop branch, if the changes are good to go?

**Comment by gpailler** [comment]
I think that this first bunch of changes can be deployed. Then we can continue to work on other improvements

**Comment by rashil2000** [comment]
Okay, please go ahead :)

**Comment by gpailler** [comment]
We're live! ;-)  https://scoopsearch.github.io/

**Comment by rashil2000** [comment]
Yay!

I'm closing this issue, as the original request is fulfilled. 

More suggestions can come in newer issues.
