### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by itsmeboy0** [ScoopSearch/ScoopSearch.WebSearchEngine#20]
Dark mode for users who don't want to burn their eyes. I hope this isn't too hard to implement.

**Comment by gpailler** [comment]
It's a great idea! I will try to find a way to implement this dark mode

**Comment by gpailler** [comment]
@itsmeboy0 Dark mode is available on https://scoopsearch.github.io/scoopsearch-dev.github.io/ for testing. Dark mode is used automatically according to the the browser/os configuration.

**Comment by itsmeboy0** [comment]
Thanks, that looks better. It's usable for me now 🥳 Maybe a toggle for it would be nice?

**Comment by gpailler** [comment]
Yep, I will check for a trigger but I will have to investigate a bit deeper as there is no builtin support for theme switching

**Comment by gpailler** [comment]
@itsmeboy0 I added a button to force dark or light mode. Please have a look on https://scoopsearch.github.io/scoopsearch-dev.github.io/

**Comment by itsmeboy0** [comment]
Weird, three buttons, unlike most websites (ex. https://spicetify.app/, dark and light mode toggle only, default to system config).

**Comment by gpailler** [comment]
Yep, the third state is used to reset to auto mode (browser/os choice). I can remove it if you think it's too much

**Comment by itsmeboy0** [comment]
Up to you, for me, I'd like the UX to be consistent with that of other websites.

**Comment by gpailler** [comment]
Ok thanks for your feedback. Let's keep the 3 states for now. I just pushed another change to improve the tooltips and properly switch from auto to the appropriate mode (if auto is light, then switch to dark...)

**Comment by rashil2000** [comment]
Implemented in #22
