### ISSUE TITLE
Search sorting suggestions

### ISSUE THREAD

**Issue by StarsbySea** [ScoopSearch/ScoopSearch.WebSearchEngine#21]
First of all thank you very much for your work, this is the best Scoop Apps manifest search tool I have ever used.

Here's a little advice on sorting the search results.

The current search sorting rules seem to be that if a keyword matches the official bucket exactly, then its official bucket results come first. If there is no exact match or no official bucket, the results are sorted in descending order by the first letter of the community bucket author's Github username.

Reference link.
With official bucket https://scoopsearch.github.io/#/apps?q=qbittorrent
Community bucket matches https://scoopsearch.github.io/#/apps?q=qbittorrent-enhanced

I hope this later sorting rule will be changed to sort by the number of Stars in the community bucket in descending order by default, so that it will be easier to find out if a software is available in a popular community bucket, and perhaps safer for users (?)

Much thanks.

**Comment by gpailler** [comment]
Hey @StarsbySea 

Thanks for your feedback. You are right, the Best Match sorting rule should probably display official buckets first then sort according the number of stars instead of alphabetically. 
I will do some tests to update the sorting rules.

Thanks

**Comment by gpailler** [comment]
@StarsbySea I applied some changes to increase the weight of the number of stars in the search results scoring. It's a bit tricky to tweak because the scoring is based on multiple fields (name, description, repo type, stars, ...) with different weights but the results look a bit better now. 

What are your thoughts?

**Comment by rashil2000** [comment]
Implemented in #22
